// AUTOGENERATED by qcbackend/scripts/gen_ts_enums.py — do not hand-edit.
// Re-run when app/enums.py or app/constants.py change.

export const AIAgentDomain = {
  PIPELINE: "pipeline",
  CLIENTS: "clients",
  BOTH: "both"
} as const;
export type AIAgentDomain = (typeof AIAgentDomain)[keyof typeof AIAgentDomain];
export const AIAgentDomainOptions = [
  { value: "pipeline", label: "Pipeline" },
  { value: "clients", label: "Clients" },
  { value: "both", label: "Both" }
] as const;

export const AIAgentKind = {
  NEW_DEAL_BUYER: "new_deal_buyer",
  NEW_DEAL_SELLER: "new_deal_seller",
  BUYER_NURTURE: "buyer_nurture",
  SELLER_FOLLOWUP: "seller_followup",
  PAST_CLIENT: "past_client",
  INVESTOR_OUTREACH: "investor_outreach",
  OPEN_HOUSE: "open_house",
  REVIEW_REQUEST: "review_request",
  CUSTOM: "custom"
} as const;
export type AIAgentKind = (typeof AIAgentKind)[keyof typeof AIAgentKind];
export const AIAgentKindOptions = [
  { value: "new_deal_buyer", label: "New Deal Buyer" },
  { value: "new_deal_seller", label: "New Deal Seller" },
  { value: "buyer_nurture", label: "Buyer Nurture" },
  { value: "seller_followup", label: "Seller Followup" },
  { value: "past_client", label: "Past Client" },
  { value: "investor_outreach", label: "Investor Outreach" },
  { value: "open_house", label: "Open House" },
  { value: "review_request", label: "Review Request" },
  { value: "custom", label: "Custom" }
] as const;

export const AIAgentLeadStatus = {
  PENDING_REVIEW: "pending_review",
  ACTIVE: "active",
  PAUSED: "paused",
  REPLIED: "replied",
  HANDED_OFF: "handed_off",
  EXITED: "exited"
} as const;
export type AIAgentLeadStatus = (typeof AIAgentLeadStatus)[keyof typeof AIAgentLeadStatus];
export const AIAgentLeadStatusOptions = [
  { value: "pending_review", label: "Pending Review" },
  { value: "active", label: "Active" },
  { value: "paused", label: "Paused" },
  { value: "replied", label: "Replied" },
  { value: "handed_off", label: "Handed Off" },
  { value: "exited", label: "Exited" }
] as const;

export const AIAgentPersonaMode = {
  VIRTUAL_SECRETARY: "virtual_secretary",
  AGENT_PERSONA: "agent_persona"
} as const;
export type AIAgentPersonaMode = (typeof AIAgentPersonaMode)[keyof typeof AIAgentPersonaMode];
export const AIAgentPersonaModeOptions = [
  { value: "virtual_secretary", label: "Virtual Secretary" },
  { value: "agent_persona", label: "Agent Persona" }
] as const;

export const AIAgentSendMode = {
  DRAFT_FIRST: "draft_first",
  AUTO: "auto"
} as const;
export type AIAgentSendMode = (typeof AIAgentSendMode)[keyof typeof AIAgentSendMode];
export const AIAgentSendModeOptions = [
  { value: "draft_first", label: "Draft First" },
  { value: "auto", label: "Auto" }
] as const;

export const AIAgentStatus = {
  DRAFT: "draft",
  NEEDS_TRAINING: "needs_training",
  TRAINING_IN_PROGRESS: "training_in_progress",
  NEEDS_REVIEW: "needs_review",
  READY_TO_ACTIVATE: "ready_to_activate",
  ACTIVE: "active",
  PAUSED: "paused",
  ARCHIVED: "archived"
} as const;
export type AIAgentStatus = (typeof AIAgentStatus)[keyof typeof AIAgentStatus];
export const AIAgentStatusOptions = [
  { value: "draft", label: "Draft" },
  { value: "needs_training", label: "Needs Training" },
  { value: "training_in_progress", label: "Training In Progress" },
  { value: "needs_review", label: "Needs Review" },
  { value: "ready_to_activate", label: "Ready To Activate" },
  { value: "active", label: "Active" },
  { value: "paused", label: "Paused" },
  { value: "archived", label: "Archived" }
] as const;

export const AITaskPriority = {
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low"
} as const;
export type AITaskPriority = (typeof AITaskPriority)[keyof typeof AITaskPriority];
export const AITaskPriorityOptions = [
  { value: "high", label: "High" },
  { value: "medium", label: "Medium" },
  { value: "low", label: "Low" }
] as const;

export const AITaskSource = {
  UNDERWRITING: "underwriting",
  MESSAGES: "messages",
  RISK: "risk",
  CALENDAR: "calendar",
  DOCUMENTS: "documents",
  PIPELINE: "pipeline",
  RATES: "rates",
  BROKER_SUGGESTION: "broker_suggestion",
  LIVE_CHAT: "live_chat"
} as const;
export type AITaskSource = (typeof AITaskSource)[keyof typeof AITaskSource];
export const AITaskSourceOptions = [
  { value: "underwriting", label: "Underwriting" },
  { value: "messages", label: "Messages" },
  { value: "risk", label: "Risk" },
  { value: "calendar", label: "Calendar" },
  { value: "documents", label: "Documents" },
  { value: "pipeline", label: "Pipeline" },
  { value: "rates", label: "Rates" },
  { value: "broker_suggestion", label: "Broker Suggestion" },
  { value: "live_chat", label: "Live Chat" }
] as const;

export const AITaskStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  DISMISSED: "dismissed",
  EXECUTED: "executed"
} as const;
export type AITaskStatus = (typeof AITaskStatus)[keyof typeof AITaskStatus];
export const AITaskStatusOptions = [
  { value: "pending", label: "Pending" },
  { value: "approved", label: "Approved" },
  { value: "dismissed", label: "Dismissed" },
  { value: "executed", label: "Executed" }
] as const;

export const AgentTaskCategory = {
  BUYER_WORKFLOW: "buyer_workflow",
  SELLER_WORKFLOW: "seller_workflow",
  FUNDING_PREP: "funding_prep",
  SHOWING: "showing",
  OPEN_HOUSE: "open_house",
  LISTING_PREP: "listing_prep",
  CMA: "cma",
  PHOTOGRAPHY: "photography",
  DOCUMENT_COLLECTION: "document_collection",
  OTHER: "other"
} as const;
export type AgentTaskCategory = (typeof AgentTaskCategory)[keyof typeof AgentTaskCategory];
export const AgentTaskCategoryOptions = [
  { value: "buyer_workflow", label: "Buyer Workflow" },
  { value: "seller_workflow", label: "Seller Workflow" },
  { value: "funding_prep", label: "Funding Prep" },
  { value: "showing", label: "Showing" },
  { value: "open_house", label: "Open House" },
  { value: "listing_prep", label: "Listing Prep" },
  { value: "cma", label: "Cma" },
  { value: "photography", label: "Photography" },
  { value: "document_collection", label: "Document Collection" },
  { value: "other", label: "Other" }
] as const;

export const AgentTaskStatus = {
  OPEN: "open",
  IN_PROGRESS: "in_progress",
  WAITING: "waiting",
  DONE: "done",
  CANCELLED: "cancelled"
} as const;
export type AgentTaskStatus = (typeof AgentTaskStatus)[keyof typeof AgentTaskStatus];
export const AgentTaskStatusOptions = [
  { value: "open", label: "Open" },
  { value: "in_progress", label: "In Progress" },
  { value: "waiting", label: "Waiting" },
  { value: "done", label: "Done" },
  { value: "cancelled", label: "Cancelled" }
] as const;

export const AgentTaskVisibility = {
  AGENT_PRIVATE: "agent_private",
  TEAM_VISIBLE: "team_visible",
  FUNDING_VISIBLE: "funding_visible",
  CLIENT_VISIBLE: "client_visible"
} as const;
export type AgentTaskVisibility = (typeof AgentTaskVisibility)[keyof typeof AgentTaskVisibility];
export const AgentTaskVisibilityOptions = [
  { value: "agent_private", label: "Agent Private" },
  { value: "team_visible", label: "Team Visible" },
  { value: "funding_visible", label: "Funding Visible" },
  { value: "client_visible", label: "Client Visible" }
] as const;

export const AmortizationStyle = {
  FULLY_AMORTIZING: "fully_amortizing",
  INTEREST_ONLY: "interest_only"
} as const;
export type AmortizationStyle = (typeof AmortizationStyle)[keyof typeof AmortizationStyle];
export const AmortizationStyleOptions = [
  { value: "fully_amortizing", label: "Fully Amortizing" },
  { value: "interest_only", label: "Interest Only" }
] as const;

export const ApprovalMode = {
  DRAFT_FIRST: "draft_first",
  AUTO_SEND_PORTAL: "auto_send_portal",
  REQUIRE_PER_MESSAGE: "require_per_message"
} as const;
export type ApprovalMode = (typeof ApprovalMode)[keyof typeof ApprovalMode];
export const ApprovalModeOptions = [
  { value: "draft_first", label: "Draft First" },
  { value: "auto_send_portal", label: "Auto Send Portal" },
  { value: "require_per_message", label: "Require Per Message" }
] as const;

export const BrokerTier = {
  BRONZE: "bronze",
  SILVER: "silver",
  GOLD: "gold",
  PLATINUM: "platinum"
} as const;
export type BrokerTier = (typeof BrokerTier)[keyof typeof BrokerTier];
export const BrokerTierOptions = [
  { value: "bronze", label: "Bronze" },
  { value: "silver", label: "Silver" },
  { value: "gold", label: "Gold" },
  { value: "platinum", label: "Platinum" }
] as const;

export const CalendarEventKind = {
  CALL: "call",
  DOC: "doc",
  AI: "ai",
  INSPECT: "inspect",
  MILESTONE: "milestone",
  LOCK: "lock",
  PAY: "pay",
  CLOSING: "closing"
} as const;
export type CalendarEventKind = (typeof CalendarEventKind)[keyof typeof CalendarEventKind];
export const CalendarEventKindOptions = [
  { value: "call", label: "Call" },
  { value: "doc", label: "Doc" },
  { value: "ai", label: "Ai" },
  { value: "inspect", label: "Inspect" },
  { value: "milestone", label: "Milestone" },
  { value: "lock", label: "Lock" },
  { value: "pay", label: "Pay" },
  { value: "closing", label: "Closing" }
] as const;

export const CalendarEventSource = {
  MANUAL: "manual",
  AUTO: "auto",
  AI: "ai"
} as const;
export type CalendarEventSource = (typeof CalendarEventSource)[keyof typeof CalendarEventSource];
export const CalendarEventSourceOptions = [
  { value: "manual", label: "Manual" },
  { value: "auto", label: "Auto" },
  { value: "ai", label: "Ai" }
] as const;

export const CalendarEventStatus = {
  PENDING: "pending",
  DONE: "done",
  CANCELLED: "cancelled"
} as const;
export type CalendarEventStatus = (typeof CalendarEventStatus)[keyof typeof CalendarEventStatus];
export const CalendarEventStatusOptions = [
  { value: "pending", label: "Pending" },
  { value: "done", label: "Done" },
  { value: "cancelled", label: "Cancelled" }
] as const;

export const CalendarExternalRefKind = {
  LOAN_STAGE: "loan_stage",
  LOAN_CLOSE: "loan_close",
  CREDIT_PULL: "credit_pull",
  CREDIT_EXPIRY: "credit_expiry",
  DOCUMENT_DUE: "document_due",
  PREQUAL_CLOSE: "prequal_close",
  AI_ACTION: "ai_action",
  STALLED_LOAN: "stalled_loan"
} as const;
export type CalendarExternalRefKind = (typeof CalendarExternalRefKind)[keyof typeof CalendarExternalRefKind];
export const CalendarExternalRefKindOptions = [
  { value: "loan_stage", label: "Loan Stage" },
  { value: "loan_close", label: "Loan Close" },
  { value: "credit_pull", label: "Credit Pull" },
  { value: "credit_expiry", label: "Credit Expiry" },
  { value: "document_due", label: "Document Due" },
  { value: "prequal_close", label: "Prequal Close" },
  { value: "ai_action", label: "Ai Action" },
  { value: "stalled_loan", label: "Stalled Loan" }
] as const;

export const ClientStage = {
  LEAD: "lead",
  CONTACTED: "contacted",
  VERIFIED: "verified",
  READY_FOR_LENDING: "ready_for_lending",
  PROCESSING: "processing",
  FUNDED: "funded",
  LOST: "lost"
} as const;
export type ClientStage = (typeof ClientStage)[keyof typeof ClientStage];
export const ClientStageOptions = [
  { value: "lead", label: "Lead" },
  { value: "contacted", label: "Contacted" },
  { value: "verified", label: "Verified" },
  { value: "ready_for_lending", label: "Ready For Lending" },
  { value: "processing", label: "Processing" },
  { value: "funded", label: "Funded" },
  { value: "lost", label: "Lost" }
] as const;

export const CompletionMode = {
  AI_CAN_COMPLETE: "ai_can_complete",
  REQUIRES_HUMAN_VERIFY: "requires_human_verify",
  BORROWER_SELF_ATTEST: "borrower_self_attest"
} as const;
export type CompletionMode = (typeof CompletionMode)[keyof typeof CompletionMode];
export const CompletionModeOptions = [
  { value: "ai_can_complete", label: "Ai Can Complete" },
  { value: "requires_human_verify", label: "Requires Human Verify" },
  { value: "borrower_self_attest", label: "Borrower Self Attest" }
] as const;

export const CreditPullStatus = {
  NONE: "none",
  PENDING: "pending",
  COMPLETED: "completed",
  EXPIRED: "expired",
  REVOKED: "revoked"
} as const;
export type CreditPullStatus = (typeof CreditPullStatus)[keyof typeof CreditPullStatus];
export const CreditPullStatusOptions = [
  { value: "none", label: "None" },
  { value: "pending", label: "Pending" },
  { value: "completed", label: "Completed" },
  { value: "expired", label: "Expired" },
  { value: "revoked", label: "Revoked" }
] as const;

export const DealAIStatus = {
  IDLE: "idle",
  ACTIVE: "active",
  PAUSED: "paused"
} as const;
export type DealAIStatus = (typeof DealAIStatus)[keyof typeof DealAIStatus];
export const DealAIStatusOptions = [
  { value: "idle", label: "Idle" },
  { value: "active", label: "Active" },
  { value: "paused", label: "Paused" }
] as const;

export const DealChatMode = {
  CHAT: "chat",
  INSTRUCT: "instruct",
  BROKER_QUESTION: "broker_question",
  BROKER_SUGGESTION: "broker_suggestion",
  LIVE_CHAT: "live_chat"
} as const;
export type DealChatMode = (typeof DealChatMode)[keyof typeof DealChatMode];
export const DealChatModeOptions = [
  { value: "chat", label: "Chat" },
  { value: "instruct", label: "Instruct" },
  { value: "broker_question", label: "Broker Question" },
  { value: "broker_suggestion", label: "Broker Suggestion" },
  { value: "live_chat", label: "Live Chat" }
] as const;

export const DealChatRole = {
  AI: "ai",
  SUPER_ADMIN: "super_admin",
  BROKER_INTERNAL: "broker_internal",
  BROKER: "broker",
  CLIENT: "client"
} as const;
export type DealChatRole = (typeof DealChatRole)[keyof typeof DealChatRole];
export const DealChatRoleOptions = [
  { value: "ai", label: "Ai" },
  { value: "super_admin", label: "Super Admin" },
  { value: "broker_internal", label: "Broker Internal" },
  { value: "broker", label: "Broker" },
  { value: "client", label: "Client" }
] as const;

export const DealHandoffStatus = {
  NONE: "none",
  REQUESTED: "requested",
  PACKET_BUILT: "packet_built",
  PROMOTED: "promoted"
} as const;
export type DealHandoffStatus = (typeof DealHandoffStatus)[keyof typeof DealHandoffStatus];
export const DealHandoffStatusOptions = [
  { value: "none", label: "None" },
  { value: "requested", label: "Requested" },
  { value: "packet_built", label: "Packet Built" },
  { value: "promoted", label: "Promoted" }
] as const;

export const DealHealth = {
  ON_TRACK: "on_track",
  AT_RISK: "at_risk",
  STUCK: "stuck"
} as const;
export type DealHealth = (typeof DealHealth)[keyof typeof DealHealth];
export const DealHealthOptions = [
  { value: "on_track", label: "On Track" },
  { value: "at_risk", label: "At Risk" },
  { value: "stuck", label: "Stuck" }
] as const;

export const DealStatus = {
  OPEN: "open",
  ACTIVE: "active",
  PAUSED: "paused",
  WON: "won",
  LOST: "lost",
  PROMOTED: "promoted"
} as const;
export type DealStatus = (typeof DealStatus)[keyof typeof DealStatus];
export const DealStatusOptions = [
  { value: "open", label: "Open" },
  { value: "active", label: "Active" },
  { value: "paused", label: "Paused" },
  { value: "won", label: "Won" },
  { value: "lost", label: "Lost" },
  { value: "promoted", label: "Promoted" }
] as const;

export const DealType = {
  BUYER: "buyer",
  SELLER: "seller",
  INVESTOR: "investor",
  BORROWER: "borrower"
} as const;
export type DealType = (typeof DealType)[keyof typeof DealType];
export const DealTypeOptions = [
  { value: "buyer", label: "Buyer" },
  { value: "seller", label: "Seller" },
  { value: "investor", label: "Investor" },
  { value: "borrower", label: "Borrower" }
] as const;

export const DocStatus = {
  PENDING: "pending",
  REQUESTED: "requested",
  RECEIVED: "received",
  FLAGGED: "flagged",
  VERIFIED: "verified",
  SKIPPED: "skipped"
} as const;
export type DocStatus = (typeof DocStatus)[keyof typeof DocStatus];
export const DocStatusOptions = [
  { value: "pending", label: "Pending" },
  { value: "requested", label: "Requested" },
  { value: "received", label: "Received" },
  { value: "flagged", label: "Flagged" },
  { value: "verified", label: "Verified" },
  { value: "skipped", label: "Skipped" }
] as const;

export const EmailDraftStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  SENT: "sent",
  DISMISSED: "dismissed"
} as const;
export type EmailDraftStatus = (typeof EmailDraftStatus)[keyof typeof EmailDraftStatus];
export const EmailDraftStatusOptions = [
  { value: "pending", label: "Pending" },
  { value: "approved", label: "Approved" },
  { value: "sent", label: "Sent" },
  { value: "dismissed", label: "Dismissed" }
] as const;

export const EntityType = {
  INDIVIDUAL: "individual",
  LLC: "llc",
  CORPORATION: "corporation",
  TRUST: "trust"
} as const;
export type EntityType = (typeof EntityType)[keyof typeof EntityType];
export const EntityTypeOptions = [
  { value: "individual", label: "Individual" },
  { value: "llc", label: "Llc" },
  { value: "corporation", label: "Corporation" },
  { value: "trust", label: "Trust" }
] as const;

export const ExitStrategy = {
  SALE: "sale",
  REFINANCE: "refinance",
  HOLD: "hold"
} as const;
export type ExitStrategy = (typeof ExitStrategy)[keyof typeof ExitStrategy];
export const ExitStrategyOptions = [
  { value: "sale", label: "Sale" },
  { value: "refinance", label: "Refinance" },
  { value: "hold", label: "Hold" }
] as const;

export const ExperienceTier = {
  NONE: "0_flips",
  LIGHT: "1_2_flips",
  MID: "3_5_flips",
  HEAVY: "5_plus_flips"
} as const;
export type ExperienceTier = (typeof ExperienceTier)[keyof typeof ExperienceTier];
export const ExperienceTierOptions = [
  { value: "0_flips", label: "0 Flips" },
  { value: "1_2_flips", label: "1 2 Flips" },
  { value: "3_5_flips", label: "3 5 Flips" },
  { value: "5_plus_flips", label: "5 Plus Flips" }
] as const;

export const FeedbackOutputType = {
  AI_TASK: "ai_task",
  CHAT_REPLY: "chat_reply",
  EMAIL_DRAFT: "email_draft",
  SUMMARY: "summary"
} as const;
export type FeedbackOutputType = (typeof FeedbackOutputType)[keyof typeof FeedbackOutputType];
export const FeedbackOutputTypeOptions = [
  { value: "ai_task", label: "Ai Task" },
  { value: "chat_reply", label: "Chat Reply" },
  { value: "email_draft", label: "Email Draft" },
  { value: "summary", label: "Summary" }
] as const;

export const FeedbackRating = {
  UP: "up",
  DOWN: "down"
} as const;
export type FeedbackRating = (typeof FeedbackRating)[keyof typeof FeedbackRating];
export const FeedbackRatingOptions = [
  { value: "up", label: "Up" },
  { value: "down", label: "Down" }
] as const;

export const LinkKind = {
  DOCUSIGN: "docusign",
  ESIGN: "esign",
  EXTERNAL_FORM: "external_form",
  REFERENCE: "reference"
} as const;
export type LinkKind = (typeof LinkKind)[keyof typeof LinkKind];
export const LinkKindOptions = [
  { value: "docusign", label: "Docusign" },
  { value: "esign", label: "Esign" },
  { value: "external_form", label: "External Form" },
  { value: "reference", label: "Reference" }
] as const;

export const LoanPurpose = {
  PURCHASE: "purchase",
  RATE_TERM_REFI: "rate_term_refi",
  CASH_OUT_REFI: "cash_out_refi"
} as const;
export type LoanPurpose = (typeof LoanPurpose)[keyof typeof LoanPurpose];
export const LoanPurposeOptions = [
  { value: "purchase", label: "Purchase" },
  { value: "rate_term_refi", label: "Rate Term Refi" },
  { value: "cash_out_refi", label: "Cash Out Refi" }
] as const;

export const LoanSide = {
  BUYER: "buyer",
  SELLER: "seller"
} as const;
export type LoanSide = (typeof LoanSide)[keyof typeof LoanSide];
export const LoanSideOptions = [
  { value: "buyer", label: "Buyer" },
  { value: "seller", label: "Seller" }
] as const;

export const LoanStage = {
  PREQUALIFIED: "prequalified",
  COLLECTING_DOCS: "collecting_docs",
  LENDER_CONNECTED: "lender_connected",
  PROCESSING: "processing",
  CLOSING: "closing",
  FUNDED: "funded"
} as const;
export type LoanStage = (typeof LoanStage)[keyof typeof LoanStage];
export const LoanStageOptions = [
  { value: "prequalified", label: "Prequalified" },
  { value: "collecting_docs", label: "Collecting Docs" },
  { value: "lender_connected", label: "Lender Connected" },
  { value: "processing", label: "Processing" },
  { value: "closing", label: "Closing" },
  { value: "funded", label: "Funded" }
] as const;

export const LoanType = {
  DSCR: "dscr",
  FIX_AND_FLIP: "fix_and_flip",
  GROUND_UP: "ground_up",
  BRIDGE: "bridge",
  PORTFOLIO: "portfolio",
  CASH_OUT_REFI: "cash_out_refi"
} as const;
export type LoanType = (typeof LoanType)[keyof typeof LoanType];
export const LoanTypeOptions = [
  { value: "dscr", label: "Dscr" },
  { value: "fix_and_flip", label: "Fix And Flip" },
  { value: "ground_up", label: "Ground Up" },
  { value: "bridge", label: "Bridge" },
  { value: "portfolio", label: "Portfolio" },
  { value: "cash_out_refi", label: "Cash Out Refi" }
] as const;

export const MessageFrom = {
  CLIENT: "client",
  BROKER: "broker",
  AI: "ai",
  LENDER: "lender"
} as const;
export type MessageFrom = (typeof MessageFrom)[keyof typeof MessageFrom];
export const MessageFromOptions = [
  { value: "client", label: "Client" },
  { value: "broker", label: "Broker" },
  { value: "ai", label: "Ai" },
  { value: "lender", label: "Lender" }
] as const;

export const OutreachChannel = {
  PORTAL: "portal",
  EMAIL: "email",
  SMS: "sms",
  WHATSAPP: "whatsapp",
  VOICE: "voice"
} as const;
export type OutreachChannel = (typeof OutreachChannel)[keyof typeof OutreachChannel];
export const OutreachChannelOptions = [
  { value: "portal", label: "Portal" },
  { value: "email", label: "Email" },
  { value: "sms", label: "Sms" },
  { value: "whatsapp", label: "Whatsapp" },
  { value: "voice", label: "Voice" }
] as const;

export const OutreachEventStatus = {
  SCHEDULED: "scheduled",
  DRAFTED: "drafted",
  SENT: "sent",
  DELIVERED: "delivered",
  RESPONDED: "responded",
  FAILED: "failed",
  BLOCKED_BY_CONSENT: "blocked_by_consent",
  BLOCKED_BY_QUIET_HOURS: "blocked_by_quiet_hours",
  BLOCKED_BY_WORKING_HOURS: "blocked_by_working_hours",
  BLOCKED_BY_POLICY: "blocked_by_policy",
  CANCELLED: "cancelled"
} as const;
export type OutreachEventStatus = (typeof OutreachEventStatus)[keyof typeof OutreachEventStatus];
export const OutreachEventStatusOptions = [
  { value: "scheduled", label: "Scheduled" },
  { value: "drafted", label: "Drafted" },
  { value: "sent", label: "Sent" },
  { value: "delivered", label: "Delivered" },
  { value: "responded", label: "Responded" },
  { value: "failed", label: "Failed" },
  { value: "blocked_by_consent", label: "Blocked By Consent" },
  { value: "blocked_by_quiet_hours", label: "Blocked By Quiet Hours" },
  { value: "blocked_by_working_hours", label: "Blocked By Working Hours" },
  { value: "blocked_by_policy", label: "Blocked By Policy" },
  { value: "cancelled", label: "Cancelled" }
] as const;

export const OutreachMode = {
  OFF: "off",
  DRAFT_FIRST: "draft_first",
  PORTAL_AUTO: "portal_auto",
  PORTAL_EMAIL: "portal_email",
  PORTAL_EMAIL_SMS: "portal_email_sms"
} as const;
export type OutreachMode = (typeof OutreachMode)[keyof typeof OutreachMode];
export const OutreachModeOptions = [
  { value: "off", label: "Off" },
  { value: "draft_first", label: "Draft First" },
  { value: "portal_auto", label: "Portal Auto" },
  { value: "portal_email", label: "Portal Email" },
  { value: "portal_email_sms", label: "Portal Email Sms" }
] as const;

export const ParticipantRole = {
  LENDER: "lender",
  BROKER: "broker",
  CLIENT: "client",
  SUPER_ADMIN: "super_admin"
} as const;
export type ParticipantRole = (typeof ParticipantRole)[keyof typeof ParticipantRole];
export const ParticipantRoleOptions = [
  { value: "lender", label: "Lender" },
  { value: "broker", label: "Broker" },
  { value: "client", label: "Client" },
  { value: "super_admin", label: "Super Admin" }
] as const;

export const PrepayPenalty = {
  P_5_4_3_2_1: "5_4_3_2_1",
  P_3_2_1: "3_2_1",
  P_2_YEAR: "2_year",
  P_1_YEAR: "1_year",
  NONE: "none"
} as const;
export type PrepayPenalty = (typeof PrepayPenalty)[keyof typeof PrepayPenalty];
export const PrepayPenaltyOptions = [
  { value: "5_4_3_2_1", label: "5 4 3 2 1" },
  { value: "3_2_1", label: "3 2 1" },
  { value: "2_year", label: "2 Year" },
  { value: "1_year", label: "1 Year" },
  { value: "none", label: "None" }
] as const;

export const PropertyType = {
  SFR: "single_family",
  UNITS_2_4: "2_4_units",
  UNITS_5_8: "5_8_units",
  MIXED_USE: "mixed_use",
  COMMERCIAL: "commercial"
} as const;
export type PropertyType = (typeof PropertyType)[keyof typeof PropertyType];
export const PropertyTypeOptions = [
  { value: "single_family", label: "Single Family" },
  { value: "2_4_units", label: "2 4 Units" },
  { value: "5_8_units", label: "5 8 Units" },
  { value: "mixed_use", label: "Mixed Use" },
  { value: "commercial", label: "Commercial" }
] as const;

export const RequirementCategory = {
  BORROWER_INFO: "borrower_info",
  PROPERTY_DATA: "property_data",
  FINANCIALS: "financials",
  CREDIT: "credit",
  AGREEMENTS: "agreements",
  INSURANCE: "insurance",
  TITLE_AND_ESCROW: "title_and_escrow",
  APPRAISAL_AND_INSPECTION: "appraisal_and_inspection",
  SCHEDULING: "scheduling",
  COMPLIANCE: "compliance",
  COMMUNICATION: "communication",
  AI_INTERNAL: "ai_internal"
} as const;
export type RequirementCategory = (typeof RequirementCategory)[keyof typeof RequirementCategory];
export const RequirementCategoryOptions = [
  { value: "borrower_info", label: "Borrower Info" },
  { value: "property_data", label: "Property Data" },
  { value: "financials", label: "Financials" },
  { value: "credit", label: "Credit" },
  { value: "agreements", label: "Agreements" },
  { value: "insurance", label: "Insurance" },
  { value: "title_and_escrow", label: "Title And Escrow" },
  { value: "appraisal_and_inspection", label: "Appraisal And Inspection" },
  { value: "scheduling", label: "Scheduling" },
  { value: "compliance", label: "Compliance" },
  { value: "communication", label: "Communication" },
  { value: "ai_internal", label: "Ai Internal" }
] as const;

export const Role = {
  SUPER_ADMIN: "super_admin",
  REGIONAL_MANAGER: "regional_manager",
  BROKER: "broker",
  LOAN_EXEC: "loan_exec",
  CLIENT: "client",
  LENDER: "lender"
} as const;
export type Role = (typeof Role)[keyof typeof Role];
export const RoleOptions = [
  { value: "super_admin", label: "Super Admin" },
  { value: "regional_manager", label: "Regional Manager" },
  { value: "broker", label: "Broker" },
  { value: "loan_exec", label: "Loan Exec" },
  { value: "client", label: "Client" },
  { value: "lender", label: "Lender" }
] as const;

export const StrEnum = {

} as const;
export type StrEnum = (typeof StrEnum)[keyof typeof StrEnum];
export const StrEnumOptions = [

] as const;

export const TaskOwnerType = {
  HUMAN: "human",
  AI: "ai",
  SHARED: "shared",
  FUNDING_LOCKED: "funding_locked"
} as const;
export type TaskOwnerType = (typeof TaskOwnerType)[keyof typeof TaskOwnerType];
export const TaskOwnerTypeOptions = [
  { value: "human", label: "Human" },
  { value: "ai", label: "Ai" },
  { value: "shared", label: "Shared" },
  { value: "funding_locked", label: "Funding Locked" }
] as const;

export const Urgency = {
  OVERDUE: "overdue",
  TODAY: "today",
  SOON: "soon",
  WEEK: "week",
  ON_TRACK: "on_track"
} as const;
export type Urgency = (typeof Urgency)[keyof typeof Urgency];
export const UrgencyOptions = [
  { value: "overdue", label: "Overdue" },
  { value: "today", label: "Today" },
  { value: "soon", label: "Soon" },
  { value: "week", label: "Week" },
  { value: "on_track", label: "On Track" }
] as const;

export const LendingLimits = {
  dscrMaxLtvPurchase: 0.8,
  dscrMaxLtvCashOut: 0.75,
  dscrMinFico: 680,
  dscrMinRatioStandard: 1.0,
  dscrMinRatioPreferred: 1.2,
  ffMaxLtc: 0.85,
  ffMaxArvLtv: 0.7,
  ffTermMinMonths: 12,
  ffTermMaxMonths: 18,
  softPullValidityDays: 90,
} as const;
