// AUTOGENERATED by qcbackend/scripts/gen_ts_enums.py — do not hand-edit.
// Re-run when app/enums.py or app/constants.py change.

export const AITaskPriority = {
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low"
} as const;
export type AITaskPriority = (typeof AITaskPriority)[keyof typeof AITaskPriority];
export const AITaskPriorityOptions = [
  { value: "high", label: "High" },
  { value: "medium", label: "Medium" },
  { value: "low", label: "Low" }
] as const;

export const AITaskSource = {
  UNDERWRITING: "underwriting",
  MESSAGES: "messages",
  RISK: "risk",
  CALENDAR: "calendar",
  DOCUMENTS: "documents",
  PIPELINE: "pipeline",
  RATES: "rates",
  BROKER_SUGGESTION: "broker_suggestion"
} as const;
export type AITaskSource = (typeof AITaskSource)[keyof typeof AITaskSource];
export const AITaskSourceOptions = [
  { value: "underwriting", label: "Underwriting" },
  { value: "messages", label: "Messages" },
  { value: "risk", label: "Risk" },
  { value: "calendar", label: "Calendar" },
  { value: "documents", label: "Documents" },
  { value: "pipeline", label: "Pipeline" },
  { value: "rates", label: "Rates" },
  { value: "broker_suggestion", label: "Broker Suggestion" }
] as const;

// Deal Workspace enums (added by hand — keep in sync with app/enums.py)
export const DealChatRole = {
  AI: "ai",
  SUPER_ADMIN: "super_admin",
  BROKER_INTERNAL: "broker_internal",
  BROKER: "broker",
  CLIENT: "client"
} as const;
export type DealChatRole = (typeof DealChatRole)[keyof typeof DealChatRole];

export const DealChatMode = {
  CHAT: "chat",
  INSTRUCT: "instruct",
  BROKER_QUESTION: "broker_question",
  BROKER_SUGGESTION: "broker_suggestion",
  LIVE_CHAT: "live_chat"
} as const;
export type DealChatMode = (typeof DealChatMode)[keyof typeof DealChatMode];

export const FeedbackOutputType = {
  AI_TASK: "ai_task",
  CHAT_REPLY: "chat_reply",
  EMAIL_DRAFT: "email_draft",
  SUMMARY: "summary"
} as const;
export type FeedbackOutputType = (typeof FeedbackOutputType)[keyof typeof FeedbackOutputType];

export const FeedbackRating = {
  UP: "up",
  DOWN: "down"
} as const;
export type FeedbackRating = (typeof FeedbackRating)[keyof typeof FeedbackRating];

export const AITaskStatus = {
  PENDING: "pending",
  APPROVED: "approved",
  DISMISSED: "dismissed",
  EXECUTED: "executed"
} as const;
export type AITaskStatus = (typeof AITaskStatus)[keyof typeof AITaskStatus];
export const AITaskStatusOptions = [
  { value: "pending", label: "Pending" },
  { value: "approved", label: "Approved" },
  { value: "dismissed", label: "Dismissed" },
  { value: "executed", label: "Executed" }
] as const;

export const BrokerTier = {
  BRONZE: "bronze",
  SILVER: "silver",
  GOLD: "gold",
  PLATINUM: "platinum"
} as const;
export type BrokerTier = (typeof BrokerTier)[keyof typeof BrokerTier];
export const BrokerTierOptions = [
  { value: "bronze", label: "Bronze" },
  { value: "silver", label: "Silver" },
  { value: "gold", label: "Gold" },
  { value: "platinum", label: "Platinum" }
] as const;

export const CalendarEventKind = {
  CALL: "call",
  DOC: "doc",
  AI: "ai",
  INSPECT: "inspect",
  MILESTONE: "milestone",
  LOCK: "lock",
  PAY: "pay",
  CLOSING: "closing"
} as const;
export type CalendarEventKind = (typeof CalendarEventKind)[keyof typeof CalendarEventKind];
export const CalendarEventKindOptions = [
  { value: "call", label: "Call" },
  { value: "doc", label: "Doc" },
  { value: "ai", label: "Ai" },
  { value: "inspect", label: "Inspect" },
  { value: "milestone", label: "Milestone" },
  { value: "lock", label: "Lock" },
  { value: "pay", label: "Pay" },
  { value: "closing", label: "Closing" }
] as const;

export const CreditPullStatus = {
  NONE: "none",
  PENDING: "pending",
  COMPLETED: "completed",
  EXPIRED: "expired",
  REVOKED: "revoked"
} as const;
export type CreditPullStatus = (typeof CreditPullStatus)[keyof typeof CreditPullStatus];
export const CreditPullStatusOptions = [
  { value: "none", label: "None" },
  { value: "pending", label: "Pending" },
  { value: "completed", label: "Completed" },
  { value: "expired", label: "Expired" },
  { value: "revoked", label: "Revoked" }
] as const;

export const DocStatus = {
  PENDING: "pending",
  REQUESTED: "requested",
  RECEIVED: "received",
  FLAGGED: "flagged",
  VERIFIED: "verified",
  SKIPPED: "skipped"
} as const;
export type DocStatus = (typeof DocStatus)[keyof typeof DocStatus];
export const DocStatusOptions = [
  { value: "pending", label: "Pending" },
  { value: "requested", label: "Requested" },
  { value: "received", label: "Received" },
  { value: "flagged", label: "Flagged" },
  { value: "verified", label: "Verified" },
  { value: "skipped", label: "Skipped" }
] as const;

export const LoanSide = {
  BUYER: "buyer",
  SELLER: "seller"
} as const;
export type LoanSide = (typeof LoanSide)[keyof typeof LoanSide];
export const LoanSideOptions = [
  { value: "buyer", label: "Buyer" },
  { value: "seller", label: "Seller" }
] as const;

export const ClientStage = {
  LEAD: "lead",
  CONTACTED: "contacted",
  VERIFIED: "verified",
  READY_FOR_LENDING: "ready_for_lending",
  PROCESSING: "processing",
  FUNDED: "funded",
  LOST: "lost"
} as const;
export type ClientStage = (typeof ClientStage)[keyof typeof ClientStage];
export const ClientStageOptions = [
  { value: "lead", label: "Lead" },
  { value: "contacted", label: "Contacted" },
  { value: "verified", label: "Verified" },
  { value: "ready_for_lending", label: "Ready for lending" },
  { value: "processing", label: "Processing" },
  { value: "funded", label: "Funded" },
  { value: "lost", label: "Lost" }
] as const;

export const EntityType = {
  INDIVIDUAL: "individual",
  LLC: "llc",
  CORPORATION: "corporation",
  TRUST: "trust"
} as const;
export type EntityType = (typeof EntityType)[keyof typeof EntityType];
export const EntityTypeOptions = [
  { value: "individual", label: "Individual" },
  { value: "llc", label: "Llc" },
  { value: "corporation", label: "Corporation" },
  { value: "trust", label: "Trust" }
] as const;

export const ExperienceTier = {
  NONE: "0_flips",
  LIGHT: "1_2_flips",
  MID: "3_5_flips",
  HEAVY: "5_plus_flips"
} as const;
export type ExperienceTier = (typeof ExperienceTier)[keyof typeof ExperienceTier];
export const ExperienceTierOptions = [
  { value: "0_flips", label: "0 Flips" },
  { value: "1_2_flips", label: "1 2 Flips" },
  { value: "3_5_flips", label: "3 5 Flips" },
  { value: "5_plus_flips", label: "5 Plus Flips" }
] as const;

export const LoanPurpose = {
  PURCHASE: "purchase",
  RATE_TERM_REFI: "rate_term_refi",
  CASH_OUT_REFI: "cash_out_refi"
} as const;
export type LoanPurpose = (typeof LoanPurpose)[keyof typeof LoanPurpose];
export const LoanPurposeOptions = [
  { value: "purchase", label: "Purchase" },
  { value: "rate_term_refi", label: "Rate Term Refi" },
  { value: "cash_out_refi", label: "Cash Out Refi" }
] as const;

export const LoanStage = {
  PREQUALIFIED: "prequalified",
  COLLECTING_DOCS: "collecting_docs",
  LENDER_CONNECTED: "lender_connected",
  PROCESSING: "processing",
  CLOSING: "closing",
  FUNDED: "funded"
} as const;
export type LoanStage = (typeof LoanStage)[keyof typeof LoanStage];
export const LoanStageOptions = [
  { value: "prequalified", label: "Prequalified" },
  { value: "collecting_docs", label: "Collecting Docs" },
  { value: "lender_connected", label: "Lender Connected" },
  { value: "processing", label: "Processing" },
  { value: "closing", label: "Closing" },
  { value: "funded", label: "Funded" }
] as const;

export const LoanType = {
  DSCR: "dscr",
  FIX_AND_FLIP: "fix_and_flip",
  GROUND_UP: "ground_up",
  BRIDGE: "bridge",
  PORTFOLIO: "portfolio",
  CASH_OUT_REFI: "cash_out_refi"
} as const;
export type LoanType = (typeof LoanType)[keyof typeof LoanType];
export const LoanTypeOptions = [
  { value: "dscr", label: "Dscr" },
  { value: "fix_and_flip", label: "Fix And Flip" },
  { value: "ground_up", label: "Ground Up" },
  { value: "bridge", label: "Bridge" },
  { value: "portfolio", label: "Portfolio" },
  { value: "cash_out_refi", label: "Cash Out Refi" }
] as const;

export const MessageFrom = {
  CLIENT: "client",
  BROKER: "broker",
  AI: "ai",
  LENDER: "lender"
} as const;
export type MessageFrom = (typeof MessageFrom)[keyof typeof MessageFrom];
export const MessageFromOptions = [
  { value: "client", label: "Client" },
  { value: "broker", label: "Broker" },
  { value: "ai", label: "Ai" },
  { value: "lender", label: "Lender" }
] as const;

export const PrepayPenalty = {
  P_5_4_3_2_1: "5_4_3_2_1",
  P_3_2_1: "3_2_1",
  P_2_YEAR: "2_year",
  P_1_YEAR: "1_year",
  NONE: "none"
} as const;
export type PrepayPenalty = (typeof PrepayPenalty)[keyof typeof PrepayPenalty];
export const PrepayPenaltyOptions = [
  { value: "5_4_3_2_1", label: "5 4 3 2 1" },
  { value: "3_2_1", label: "3 2 1" },
  { value: "2_year", label: "2 Year" },
  { value: "1_year", label: "1 Year" },
  { value: "none", label: "None" }
] as const;

export const PropertyType = {
  SFR: "single_family",
  UNITS_2_4: "2_4_units",
  UNITS_5_8: "5_8_units",
  MIXED_USE: "mixed_use",
  COMMERCIAL: "commercial"
} as const;
export type PropertyType = (typeof PropertyType)[keyof typeof PropertyType];
export const PropertyTypeOptions = [
  { value: "single_family", label: "Single Family" },
  { value: "2_4_units", label: "2 4 Units" },
  { value: "5_8_units", label: "5 8 Units" },
  { value: "mixed_use", label: "Mixed Use" },
  { value: "commercial", label: "Commercial" }
] as const;

export const Role = {
  SUPER_ADMIN: "super_admin",
  BROKER: "broker",
  LOAN_EXEC: "loan_exec",
  CLIENT: "client"
} as const;
export type Role = (typeof Role)[keyof typeof Role];
export const RoleOptions = [
  { value: "super_admin", label: "Super Admin" },
  { value: "broker", label: "Broker" },
  { value: "loan_exec", label: "Loan Exec" },
  { value: "client", label: "Client" }
] as const;

export const StrEnum = {

} as const;
export type StrEnum = (typeof StrEnum)[keyof typeof StrEnum];
export const StrEnumOptions = [

] as const;

export const Urgency = {
  OVERDUE: "overdue",
  TODAY: "today",
  SOON: "soon",
  WEEK: "week",
  ON_TRACK: "on_track"
} as const;
export type Urgency = (typeof Urgency)[keyof typeof Urgency];
export const UrgencyOptions = [
  { value: "overdue", label: "Overdue" },
  { value: "today", label: "Today" },
  { value: "soon", label: "Soon" },
  { value: "week", label: "Week" },
  { value: "on_track", label: "On Track" }
] as const;

export const LendingLimits = {
  dscrMaxLtvPurchase: 0.8,
  dscrMaxLtvCashOut: 0.75,
  dscrMinFico: 680,
  dscrMinRatioStandard: 1.0,
  dscrMinRatioPreferred: 1.2,
  ffMaxLtc: 0.85,
  ffMaxArvLtv: 0.7,
  ffTermMinMonths: 12,
  ffTermMaxMonths: 18,
  softPullValidityDays: 90,
} as const;
