// Fix & Flip Deal Analyzer — curated lending program catalog.
// Credit score is the PRIMARY gatekeeper, experience secondary, then
// the F&F leverage caps. Calibrated to the real backend constants
// (FF_MAX_LTC 0.85 / FF_MAX_ARV_LTV 0.70; DSCR_MIN_FICO 680;
// ExperienceTier 0_flips|1_2_flips|3_5_flips|5_plus_flips). Illustrative,
// not contractual — outputs are always labeled estimates.
// BYTE-IDENTICAL between QCDashboard and QCMobile.

import type { LendingProgram } from "./types";

export const LENDING_PROGRAMS: LendingProgram[] = [
  {
    id: "ff-core-680",
    name: "Fix & Flip Core",
    programType: "fix_flip",
    minCreditScore: 680,
    minExperience: "1_2_flips",
    maxLTC: 0.85,
    maxARVLTV: 0.70,
    maxPurchaseFundingPct: 0.85,
    maxRehabFundingPct: 1.0,
    interestRate: 0.1075,
    points: 2,
    termMonths: 12,
    allowsFirstTimeFlipper: false,
    allowsConstructionReserve: true,
    allowsInterestReserve: true,
    notes: "Best leverage for experienced borrowers with solid credit.",
  },
  {
    id: "ff-prime-720",
    name: "Fix & Flip Prime",
    programType: "fix_flip",
    minCreditScore: 720,
    minExperience: "3_5_flips",
    maxLTC: 0.85,
    maxARVLTV: 0.70,
    maxPurchaseFundingPct: 0.90,
    maxRehabFundingPct: 1.0,
    interestRate: 0.0975,
    points: 1.5,
    termMonths: 12,
    allowsFirstTimeFlipper: false,
    allowsConstructionReserve: true,
    allowsInterestReserve: true,
    notes: "Lowest cost of capital — strong credit + track record.",
  },
  {
    id: "ff-starter-640",
    name: "Fix & Flip Starter",
    programType: "fix_flip",
    minCreditScore: 640,
    minExperience: "0_flips",
    maxLTC: 0.80,
    maxARVLTV: 0.65,
    maxPurchaseFundingPct: 0.80,
    maxRehabFundingPct: 1.0,
    interestRate: 0.1175,
    points: 3,
    termMonths: 12,
    allowsFirstTimeFlipper: true,
    allowsConstructionReserve: true,
    allowsInterestReserve: false,
    notes: "First-time flippers OK; lower leverage, higher cost.",
  },
  {
    id: "bridge-660",
    name: "Bridge / Light Rehab",
    programType: "bridge",
    minCreditScore: 660,
    minExperience: "0_flips",
    maxLTC: 0.80,
    maxARVLTV: 0.70,
    maxPurchaseFundingPct: 0.85,
    maxRehabFundingPct: 0.0,
    interestRate: 0.1050,
    points: 2,
    termMonths: 12,
    allowsFirstTimeFlipper: true,
    allowsConstructionReserve: false,
    allowsInterestReserve: true,
    notes: "Purchase-only leverage; rehab funded by borrower.",
  },
  {
    id: "construction-700",
    name: "Heavy Construction",
    programType: "construction",
    minCreditScore: 700,
    minExperience: "3_5_flips",
    minLiquidity: 75000,
    maxLTC: 0.85,
    maxARVLTV: 0.70,
    maxPurchaseFundingPct: 0.85,
    maxRehabFundingPct: 1.0,
    interestRate: 0.1150,
    points: 2.5,
    termMonths: 18,
    allowsFirstTimeFlipper: false,
    allowsConstructionReserve: true,
    allowsInterestReserve: true,
    notes: "Longer term for heavy/ground-up scopes; experienced only.",
  },
  {
    id: "ff-pro-760",
    name: "Fix & Flip Pro",
    programType: "fix_flip",
    minCreditScore: 760,
    minExperience: "5_plus_flips",
    minLiquidity: 100000,
    maxLTC: 0.90,
    maxARVLTV: 0.75,
    maxPurchaseFundingPct: 0.92,
    maxRehabFundingPct: 1.0,
    interestRate: 0.0925,
    points: 1,
    termMonths: 12,
    allowsFirstTimeFlipper: false,
    allowsConstructionReserve: true,
    allowsInterestReserve: true,
    notes: "Top-tier leverage + pricing for professional operators.",
  },
];
